# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dhruv160410116084 < Formula
  desc ""
  homepage "https://github.com/dhruv160410116084/sshm"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.3/sshm_1.1.3_Darwin_x86_64.tar.gz"
      sha256 "63c2e55ca31c7568d44c2aaa397365778a440d9e88c609b2808a340deadec615"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.3/sshm_1.1.3_Darwin_arm64.tar.gz"
      sha256 "ee788945dc8886eabda5f2a053dc8d880e364bd780bae3ba598adc607f3531a9"

      def install
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.3/sshm_1.1.3_Linux_arm64.tar.gz"
      sha256 "9593df7db4132d46c41b71c4420018bfb3f3699914e2a282327026e9ca1bab52"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.3/sshm_1.1.3_Linux_x86_64.tar.gz"
      sha256 "521ff65c80c04886d783c2ee8c0b967001b98ddf633fe90bd814a2a5b95a30bb"

      def install
        bin.install "sshm"
      end
    end
  end
end
