# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sshm < Formula
  desc ""
  homepage "https://github.com/dhruv160410116084/sshm"
  version "1.1.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.5/sshm_1.1.5_Darwin_arm64.tar.gz"
      sha256 "85047b6b9aa0ad00bbacc248959ba452330097fd884dea17685fcdfc45c977cb"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.5/sshm_1.1.5_Darwin_x86_64.tar.gz"
      sha256 "6e4f9f6118b649154decf05e831b6392c3d964c2c51d805fc23c4ee9444c3d8c"

      def install
        bin.install "sshm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.5/sshm_1.1.5_Linux_x86_64.tar.gz"
      sha256 "68ce17dc70d7641ba28512d00cafce789da7c216c6ca8c828ead1036242315c4"

      def install
        bin.install "sshm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dhruv160410116084/sshm/releases/download/v1.1.5/sshm_1.1.5_Linux_arm64.tar.gz"
      sha256 "b20e7a318651326ab63ad0d4c505ec3205d61f4807fdc5acd278058e1cf5055c"

      def install
        bin.install "sshm"
      end
    end
  end
end
